#!/bin/bash

if [ -n "$1" ];then
    ssh -t $1 'if [ -f /bin/dnf -o -f /usr/bin/dnf ];then IST="dnf"; else if [ -f /bin/yum -o -f /usr/bin/yum ];then IST="yum"; else if [ -f /usr/apt-get -o -f /usr/bin/apt-get ];then IST="apt-get"; else echo "Error: package installer not found."; exit 1; fi; fi; fi; if [ ! -f /bin/git ];then sudo $IST -y update; sudo $IST -y install git git-extras; fi; if [ ! -f /bin/which -a ! -f /usr/bin/which ];then sudo \$IST -y install which; fi; if [ -d "./burmilla_os_efi" ]; then git-force-clone  https://github.com/Yougain/burmilla_os_efi.git ~/burmilla_os_efi; else git clone https://github.com/Yougain/burmilla_os_efi.git; fi; ./burmilla_os_efi/'${0##*/}'; exit $?'
    mkdir -p ~/burmilla_os_iso/
    scp $1:burmilla_os_iso/'*.iso' ~/burmilla_os_iso/
    exit $?
fi

sudo apt-get install -y make patch apt-utils


if [ ! -e /usr/lib/docker/cli-plugins/docker-buildx ];then
	#TAG=`wget -q https://github.com/docker/buildx/releases/latest -O - | grep Welcome | head -1 | grep -o -e 'v[0-9][^ "]*' | head -1`
	#sudo mkdir -p /usr/lib/docker/cli-plugins
	#sudo wget https://github.com/docker/buildx/releases/download/$TAG/buildx-$TAG.linux-amd64 -O /usr/lib/docker/cli-plugins/docker-buildx
	#sudo chmod +x /usr/lib/docker/cli-plugins/docker-buildx
	#docker buildx install
	git-force-clone https://github.com/docker/buildx.git ~/buildx
	sudo apt-get install -y make
	cd ~/buildx
	make install
	sudo mv -f $HOME/.docker/cli-plugins/docker-buildx /usr/lib/docker/cli-plugins/
	cd ~
fi

git-force-clone https://github.com/burmilla/os.git ~/os
ODIR=`pwd`
cd ~/os
patch -p1 < $ODIR/burmilla_os_efi/mountOpt.patch
sudo make
cd ~/
mkdir -p ~/burmilla_os_iso
OS_V=`grep -o -e 'VERSION=.*' os/build/initrd/usr/share/ros/os-release`
OS_VER=${OS_V#VERSION=*}
cp ~/os/dist/artifacts/burmillaos.iso ~/burmilla_os_iso/burmillaos-$OS_VER.iso


