#!/bin/bash

if [ "`id | awk '{print $1}'`" != "uid=0(root)" ];then
	sudo $0 $@
	exit $?
fi

if [ ! -x "`which gdisk`" ]; then
	apt-get install -y gdisk
fi
if [ ! -x "`which btrfs`" ]; then
	apt-get install -y btrfs-progs
fi


if [ "$1" = "" ];then
	echo "Error: Argument missing."
	exit 1
fi


if [ "${1:0:7}" != "/dev/sd" -o "${1:8}" != "" ];then
	echo "cannot use device, $1."
	exit 1
fi
if [ ! -e "$1" ];then
	echo "$1 is not existing."
	exit 1
fi

TARGET_DISK=$1
HOME_DEV=`mount | grep /home | awk '{print \$1}'` # should be OEM disk  (symlinked)
BOOT_DISK=${HOME_DEV:0:8}
if [ "${BOOT_DISK:0:7}" != "/dev/sd" ]; then
	echo "device of '/home' is not a /dev/sd? device."
	exit 1
fi

if [ "$BOOT_DISK" = "$1" ]; then
	echo "'$1' is same as boot disk."
	exit 1
fi

function sectors(){
	local GRES="`gdisk $1 <<EOF
p
q
EOF`"
	echo "$GRES"|grep "Command (? for help): Disk "|awk '{print $7 " " $8 " " $9 " " $10}'
}

BOOT_DISK_S_LINE=`sectors $BOOT_DISK`
TARGET_DISK_S_LINE=`sectors $1`
BOOT_DISK_SSIZE=`echo $BOOT_DISK_S_LINE|awk '{print $1}'`
TARGET_DISK_SSIZE=`echo $TARGET_DISK_S_LINE|awk '{print $1}'`
BOOT_DISK_SZ=`echo $BOOT_DISK_S_LINE|awk '{print $3 " " $4}'`
TARGET_DISK_SZ=`echo $TARGET_DISK_S_LINE|awk '{print $3 " " $4}'`

if [ $TARGET_DISK_SSIZE -lt $BOOT_DISK_SSIZE ];then
	echo "Target disk ($TARGET_DISK) sector size, $TARGET_DISK_SSIZE is less than boot disk ($BOOT_DISK) sector size, $BOOT_DISK_SSIZE."
	exit 1
fi

echo "BOOT DISK  : $BOOT_DISK, $BOOT_DISK_SSIZE sectors ($BOOT_DISK_SZ)"
echo "TARGET DISK: $TARGET_DISK, $TARGET_DISK_SSIZE sectors ($TARGET_DISK_SZ)"

dd if=/dev/zero of=$TARGET_DISK bs=1G count=1
partprobe

#copy partition table
GRES="`gdisk $BOOT_DISK <<EOH
x
u
$TARGET_DISK
y
q
EOH`"
partprobe
#randomize guiid of target disk
gdisk $TARGET_DISK <<EOF
x
f
w
EOF

echo "$GRES"|egrep -o '^The operation.*|writing.*'
partprobe

# copy bios boot partition
echo copying "$BOOT_DISK"1 to "$TARGET_DISK"1 ...
dd if="$BOOT_DISK"1 of="$TARGET_DISK"1
echo done
# copy efi partition
echo copying "$BOOT_DISK"2 to "$TARGET_DISK"2 ...
dd if="$BOOT_DISK"2 of="$TARGET_DISK"2
echo done

#randomize uuid of efi partition
EUUID=`xxd -u -l 2 -p /dev/urandom`-`xxd -u -l 2 -p /dev/urandom`
printf "\x${EUUID:7:2}\x${EUUID:5:2}\x${EUUID:2:2}\x${EUUID:0:2}" \
| dd bs=1 seek=67 count=4 conv=notrunc of="$TARGET_DISK"2
partprobe
if ! mkswap -L RANCHER_SWAP_SIBLING "$TARGET_DISK"3
	echo "cannot create swap partition"
	exit 1
fi

dd if=/dev/zero of="$TARGET_DISK"4 bs=100M count=1
dd if=/dev/zero of="$TARGET_DISK"5 bs=100M count=1
dd if=/dev/zero of="$TARGET_DISK"7 bs=100M count=1
partprobe

# copy boot partition to new disk (optional)
# mkdir -p /tmp/{src,dst}
# mount "$BOOT_DISK"4 /tmp/src
# mount "$TARGET_DISK"4 /tmp/dst
#cp -av /tmp/src/* /tmp/dst
# umount /tmp/src /tmp/dst

# remove missing device
btrfs device delete missing /boot
btrfs device delete missing /state_top_lvl
btrfs device delete missing /oem_top_lvl

# add new device
btrfs device add "$TARGET_DISK"4 /boot
btrfs device add "$TARGET_DISK"5 /state_top_lvl
btrfs device add "$TARGET_DISK"7 /oem_top_lvl

# select raid mode and start balancing
function bstart(){
	local dnum=`btrfs filesystem filesystem show $1 | egrep -o "Total devices [0-9]*" | awk '{print $3}'`
	case "$dnum" in
		"2" ) btrfs balance start -mconvert=raid1 -dconvert=raid1 $2 ;;
		"3" ) btrfs balance start -mconvert=raid1c3 -dconvert=raid1c3 $2 ;;
		"4" ) btrfs balance start -mconvert=raid1c4 -dconvert=raid1c4 $2 ;;
	esac
}

for uuid in `ls /dev/disk/by-uuid`; do
	case "`readlink /dev/disk$uuid`" in
		"$BOOT_DISK"4 ) bstart $uuid ;;
		"$BOOT_DISK"5 ) bstart $uuid ;;
		"$BOOT_DISK"7 ) bstart $uuid ;;
	esac
done

