#!/bin/bash

if [ -z "$1" ];then
	echo -e "\033[31mError: Missing argument (IP address for installation)\033[m"
	exit 1
fi

KEY=`cat ~/.ssh/id_ed25519.pub`
echo $KEY
if [ -z "$KEY" ];then
	echo -e "\033[31mError: Cannot find public key in ~/.ssh/id_ed25519.pub. exit.\033[m"
	exit 1
fi
if ! ssh -o "PasswordAuthentication no" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -l rancher $1 echo; then
	expect -c "
set timeout 1
spawn ssh -o \"StrictHostKeyChecking no\" -o \"UserKnownHostsFile /dev/null\" -l rancher $1
expect \"assword:\"
send \"rancher\n\"
expect \"rancher ~]$ \"
send \"mkdir ~/.ssh\n\"
expect \"rancher ~]$ \"
send \"chmod 700 ~/.ssh\n\"
expect \"rancher ~]$ \"
send \"echo $KEY > ~/.ssh/authorized_keys\n\"
expect \"rancher ~]$ \"
send \"exit\"
"
fi

if ! ssh -o "PasswordAuthentication no" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -l rancher $1 echo; then
	echo -e "\033[31mError: Cannot logon as user, 'rancher' by password, 'rancher'\033[m"
	echo "Please enter following commands on console"
	echo -e "\033[36msudo passwd rancher
rancher
rancher\033[m"
	exit 1
fi

DISK_SIZE=`ssh -o "PasswordAuthentication no" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -l rancher -t 198.19.24.196 sudo bash -c "'"sudo fdisk -l /dev/sda \|grep \"Disk /dev/sda\"\|awk \"{print $\"\"5}\""'"|grep -v boundary`
MEM_SIZE=`ssh -o "PasswordAuthentication no" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -l rancher -t 198.19.24.196 bash -c "'"cat /proc/meminfo\|grep MemTotal\|awk \"{print $\"\"2}\""'"`
DISK_SIZE=${DISK_SIZE%$'\r'}
MEM_SIZE=${MEM_SIZE%$'\r'}

if [ "$DISK_SIZE" -ge 1099511627776 ];then # over 1Tbytes
    SWAP_PART_SIZE="+64G"
else
	SWAP_PART_SIZE="+$MEM_SIZE"K
fi

ssh -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -l rancher $1 sudo ros console switch ubuntu -f
sleep 5
ssh -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -l rancher $1 bash -c "cat - > __install_rancher" <<FINAL
#!/bin/bash
apt-get update; apt-get install -y gdisk lvm2 dosfstools btrfs-tools parted
dd if=/dev/zero of=/dev/sda bs=1G count=1
partprobe
gdisk /dev/sda <<EOF
2
x
l
1
m
n
1

2047
ef02
x
l
2048
m
n
2

+256M
ef00
n
3

$SWAP_PART_SIZE
8200
n
4

+1G
8300
n
5


8300
p
w
y
EOF
partprobe
gdisk -l /dev/sda
mkswap -L RANCHER_SWAP /dev/sda3 <<END
y
END
mkfs.vfat -F32 -n EFI /dev/sda2 << END
y
END
echo -n "mounts:
- - /dev/sda5
  - /
  - btrfs
  - \"subvol=/state_root,defaults,noatime\"
- - /dev/sda5
  - /snapshots
  - btrfs
  - \"subvol=/snapshots,defaults,noatime\"
- - /dev/sda5
  - /data
  - btrfs
  - \"subvol=/data,defaults,noatime\"
- - /dev/sda5
  - /btrfs_top_lvl
  - btrfs
  - \"subvol=/,defaults,noauto,noatime\"
- - /dev/sda4
  - /boot
  - btrfs
  - \"\"
- - /dev/sda2
  - /boot/efi
  - vfat
  - \"\"
" > cloud-config.yml
echo "runcmd:
- swapon -L RANCHER_SWAP
" >> cloud-config.yml
echo -n -e "#cloud-config\nssh_authorized_keys:\n - " >> cloud-config.yml
echo "$KEY" >> cloud-config.yml
ros install -t gptsyslinux -c cloud-config.yml -a rancher.state.mdadm_scan -a rancher.state.lvm_scan -d /dev/sda -p /dev/sda4 <<END
y
n
END
mkdir /mnt/efipart && mount /dev/sda2 /mnt/efipart
mkdir /mnt/installer && mount /dev/sdb1 /mnt/installer
cp -r /mnt/installer/EFI /mnt/efipart
cat - > /mnt/efipart/EFI/BOOT/grub.cfg <<END
set timeout=1
set gfxmode=1280x1024x16
set gfxpayload=keep
menuentry "Rancher from GPT" {
	set gfxmode=1280x1024
	set gfxpayload=keep
    search --no-floppy --set=root --label RANCHER_BOOT
    linux    /vmlinuz-4.14.138-rancher nomodeset vga=775 video=1280x1024 printk.devkmsg=on rancher.state.mdadm_scan rancher.state.lvm_scan rancher.state.dev=LABEL=RANCHER_STATE rancher.state.wait panic=10 console=tty1 console=ttyS0 root=/dev/sda5 rw rootflags=subvol=/state_root
    initrd   /initrd-v1.5.8
}
END
mount /dev/sda4 /opt
mkfs.btrfs -L RANCHER_STATE -f /dev/sda5
mount /dev/sda5 /mnt
btrfs subvolume create /mnt/state_root
btrfs subvolume set-default \`btrfs subvolume list /mnt|grep state_root|awk '{print \$2}'\` /mnt
btrfs subvolume create /mnt/snapshots
btrfs subvolume create /mnt/data
mkdir /mnt/state_root/snapshots
mkdir /mnt/state_root/data
mkdir /mnt/state_root/btrfs_top_lvl
cp -av /opt/* /mnt/state_root
umount /opt
mkfs.btrfs -L RANCHER_BOOT -f /dev/sda4
mount /dev/sda4 /opt
cp -av /mnt/state_root/boot/* /opt/
rm -rf /mnt/state_root/boot/*
umount /mnt /opt
reboot
FINAL
ssh -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -l rancher $1 chmod +x __install_rancher
ssh -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -t -l rancher $1 sudo ./__install_rancher
