#!/bin/bash


source $(dirname "$(realpath -s "$0")")/bashlib_y

require create_initrd_mod


KEY=`cat ~/.ssh/id_ed25519.pub 2>/dev/null`
if [ -z "$KEY" ];then
	err Cannot find public key in ~/.ssh/id_ed25519.pub.
fi
exit_if_err


ssh_param $1 -x -q -o "PasswordAuthentication no" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -l rancher
if ! ssh_do echo -n; then
	if ! install_ssh_key; then
		die "Cannot log on as user, 'rancher' by password, 'rancher'.
$cyan"Please enter following commands on console."
	sudo passwd rancher
	rancher
	rancher"
	fi
	exit 1
	ssh_sudo <<END
		apt-get -y update
		apt-get -y install vim
END
	ssh_do <<END
		echo '
set t_Co=256
set fileencoding=japan
set fileencodings=utf-8
set tabstop=4
let $LANG='ja_JP.UTF-8'
set encoding=utf-8
set backspace=indent,eol,start

if &term == "xterm"
  let &t_ti = &t_ti . "\e[?2004h"
  let &t_te = "\e[?2004l" . &t_te
  let &pastetoggle = "\e[201~"

  function XTermPasteBegin(ret)
    set paste
    return a:ret
  endfunction

  map <special> <expr> <Esc>[200~ XTermPasteBegin("i")
  imap <special> <expr> <Esc>[200~ XTermPasteBegin("")
  cmap <special> <Esc>[200~ <nop>
  cmap <special> <Esc>[201~ <nop>
endif
' > .vimrc
END
fi

ssh_i


